[dalle]
number = 1
alternatives = ['d']

[help]
number = 0
alternatives = ['h', 'x']

[output]
number = 1
alternatives = ['o']

[version]
number = 0
alternatives = ['V']

[vqgan]
number = 1
alternatives = ['v']

